---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: song-library
  namespace: karaoke
spec:
  chart:
    spec:
      chart: ./song-library
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: karaoke-helm
  interval: 10m0s
